[package]
name = "proc-macro-error3"
authors = [
  "CreepySkeleton <creepy-skeleton@yandex.ru>",
  "GnomedDev <david2005thomas@gmail.com>",
]
version = "3.0.0"
description = "Almost drop-in replacement to panics in proc-macros"
repository = "https://github.com/GnomedDev/proc-macro-error-3"
rust-version = "1.61"
keywords = ["proc-macro", "error", "errors"]
categories = ["development-tools::procedural-macro-helpers"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
proc-macro-error-attr3 = { path = "./proc-macro-error-attr", version = "=3.0.0" }
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
default-features = false
optional = true
version = "2"

[dev-dependencies]
syn = { version = "2", features = ["full"] }
test-crate = { path = "./test-crate" }
trybuild = { version = "1.0.99", features = ["diff"] }

[features]
default = ["syn-error"]
nightly = []
syn-error = ["dep:syn"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(run_ui_tests)'] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = { level = "allow" }
